"""initial migration

Revision ID: b010436d25ce
Revises: 48a75cf734ea
Create Date: 2024-09-09 10:52:53.564239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b010436d25ce'
down_revision: Union[str, None] = '48a75cf734ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soccer_name', sa.String(), nullable=True),
    sa.Column('foundation_date', sa.String(), nullable=True),
    sa.Column('amount_titles', sa.Integer(), nullable=True),
    sa.Column('stadium', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('soccer_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clubs')
    # ### end Alembic commands ###
